image: Visual Studio 2015

clone_folder: C:\projects\sqlpp11-connector-postgresql

branches:
  only:
  - master
  - develop

environment:
  matrix:
    - GENERATOR: "Visual Studio 14"
      CONFIG: Debug
    - GENERATOR: "Visual Studio 14"
      CONFIG: Release
    - GENERATOR: "Visual Studio 15"
      CONFIG: Debug
    - GENERATOR: "Visual Studio 15"
      CONFIG: Release

services:
  - postgresql101

init:
  - set arch=
  - if "%arch%"=="Win64" ( set arch= Win64)
  - echo %arch%
  - echo %APPVEYOR_BUILD_WORKER_IMAGE%
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2017" ( set generator="Visual Studio 15 2017%arch%" )
  - if "%APPVEYOR_BUILD_WORKER_IMAGE%"=="Visual Studio 2015" ( set generator="Visual Studio 14 2015%arch%" )
  - echo %generator%

build_script:
  - PATH=C:\Program Files\PostgreSQL\9.6\bin\;%PATH%
  - set PGUSER=postgres
  - set PGPASSWORD=Password12!
  - createuser -l -S -D -R -w test
  - createdb test
  - cd ..
  - git clone --branch v2.4 --depth 1 https://github.com/HowardHinnant/date.git
  - git clone --branch master --depth 1 https://github.com/rbock/sqlpp11.git
  - cd sqlpp11
  - cmake . -DHinnantDate_ROOT_DIR="%cd%/../date"
  - cd ../sqlpp11-connector-postgresql
  - mkdir build
  - cd build
  - cmake .. -DCMAKE_PREFIX_PATH="C:/Program Files" -DDATE_INCLUDE_DIR="%cd%/../../date" -DENABLE_TESTS=True -G %generator%
  - cmake --build . --config %configuration%
  - ctest . --config %configuration